lst = ["akash", 1, True]
print(lst)

attendees = ["rock","star","akash"]
attendees.insert (1, "bingi")
print(attendees)

attendees = ["akash", "naveen", "sai", "shritha"]
print(attendees.count ("sai"))

attendees = ["naveen","akash","sai","teja"]
if [attendees.count ("balu")]:
    print(attendees)

attendees=["akash","naveen","teja"]
attendees[1] = "star akash"
print (attendees)

attendees=["shritha","naveen","badri"]
attendees1 =["sonu","limba","raju"]
attendees.extend (attendees1)
print(attendees)
print(attendees1)

attendees =["badri","sonu","akash"]
attendees.remove("akash")
print(attendees)

attendees =["akash","sonu","badri"]
attendees.pop(1)
print(attendees)

attendees=["naveen","akash","badri","sonu","nagesh"]
attendees.pop()
attendees.pop()
print(attendees)
